### ISSUE TITLE
URL Shortener for common users

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/Shorty#2]
Currently, the site can shorten URLs for authenticated users only. But need to add Shortener for common users too.

Do follow the contributions guidelines and do not make such changes which breaks the code😥

**Comment by hsrambo07** [comment]
Hey i would like to contribute to this issue.

**Comment by ashutoshkrris** [comment]
@hsrambo07 You're welcome buddy.
Once you're ready to make a PR, please refer to these [instructions](https://github.com/ashutoshkrris/Shorty/blob/master/contributors/README.md) to get yourself added in the [Contributors](https://ashutoshkrris.github.io/Shorty/) page.
See you there!

**Comment by hsrambo07** [comment]
Thanks

**Comment by JigarJoshi04** [comment]
are you still working on it @hsrambo07 ?
if you are not free, I can do this.
Do let me know

**Comment by ashutoshkrris** [comment]
> are you still working on it @hsrambo07 ?
> if you are not free, I can do this.
> Do let me know

Yeah, please go ahead.
